### PR TITLE
Base implementation for Consent support 

### PR DESCRIPTION
**Pull request by UlfBj**

### CODE REVIEW

**Comment by UlfBj** [comment]
@petervolvowinz, and everyone else using this server:
Please observe that this PR requires that the binary file containing the VSS tree is regenerated (make binary) as there is an update of the tree parser.

**Comment by petervolvowinz** [comment]
Current instructions to generate the tree binary involves cloning the VSS repo. Is there a branch with these changes pushed to the VSS repo ?

**Comment by UlfBj** [comment]
The changes was done at the Vss-tools quite some time ago, so it has
migrated to vss.
The reason vissv2 had not followed until now was a replace statement in
go.mod

**Comment by petervolvowinz** [comment]
Ok, verified the generation of the binary file. Some corrections needed in the readme instructions for the instructions in the readme will.  pull request on its way in vss-tools.

**Review by petervolvowinz — APPROVED** [review]

**Pull request merged**
